### ISSUE TITLE
TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by DLST** [LazerUnicorns/node-adblock-proxy#4]
Hello. When run node-adblock-proxy get the following error:
```bash
root@debian:/opt/node-adblock-proxy/bin# nodejs proxy --host=192.168.1.1 --port=8088 --protocol=http
{ host: '192.168.1.1',
  port: 8088,
  protocol: 'http',
  public: true }
HTTP Proxy created on null:8088
filter/Adblockplus: 14 host rules
filter/Adblockplus: 1985 path rules
filter/Adblockplus: 1681 complex rules
filter/Adblockplus: 23 host rules
filter/Adblockplus: 3725 path rules
filter/Adblockplus: 1812 complex rules
filter/Adblockplus: 23 host rules
filter/Adblockplus: 4049 path rules
filter/Adblockplus: 1871 complex rules
filter/Hosts: 10782 host rules
filter/Hosts: 22846 host rules
filter/Adblockplus: 55 host rules
filter/Adblockplus: 9130 path rules
filter/Adblockplus: 4511 complex rules
/opt/node-adblock-proxy/lib/protocol/HTTP.js:47
						protocol: options.protocol.split(':')[0],
						                          ^
TypeError: Cannot read property 'split' of null
    at Server.<anonymous> (/opt/node-adblock-proxy/lib/protocol/HTTP.js:47:33)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```
The error occurs when accessing the proxy server. I am using Debian Wheezy, node v0.12.1.

**Comment by martensms** [comment]
Sorry for the late reply, I kind of have overseen the email for this issue.

What kind of URL did you request in the browser when this error appeared? What kind of Browser do you use?

It basically means that the web browser didn't submit the protocol URL, so it's hard to reproduce on my environment (Ubuntu 14.10). Also, I'm trying to figure out what to do then - if a "polyfill" of http is the best case or not.

**Comment by martensms** [comment]
Can you verify this issue doesn't occur anymore?
Please reopen this issue again if it does.

**Comment by DLST** [comment]
Thank you very much! Now everything works great if I specify in the settings of the proxy server on the Ubuntu operating system.

Last time, as I recall, I used to do so:
1. Run the proxy server on Debian.
2. In the iptables rules stated:
```bash
iptables -t nat -A PREROUTING -s 192.168.1.3 -p tcp --dport 80 -j DNAT --to 192.168.1.1:8088
```
3. Opened URL on host 192.168.1.3

Now the program does not crash, but we can't go on any website. Tell me, please, how you can do the redirect with iptables?
